version: '3'

services:

    server:
        build:
            context: 'tests/server'
        ports:
            - 4000:4000
        networks:
            - default

    client:
        build:
            context: 'tests/client'
        environment:
            - PYTHONUNBUFFERED=1
        volumes:
            - ./tests/client/src:/src
        networks:
            - default

networks:
    default:
        driver: bridge