# Generated by Django 4.0.2 on 2022-10-17 17:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('teaser_text', models.CharField(max_length=1047)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleAuthorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('filename', models.CharField(max_length=1047)),
                ('description', models.CharField(max_length=1047)),
                ('caption', models.CharField(blank=True, max_length=1047, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImagePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fractional_index', models.FloatField(blank=True, default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RichTextBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locked', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RichTextBlockPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fractional_index', models.FloatField(blank=True, default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RichTextSpan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote', models.BooleanField(default=False)),
                ('strong', models.BooleanField(default=False)),
                ('emphasis', models.BooleanField(default=False)),
                ('href', models.CharField(blank=True, max_length=1047, null=True)),
                ('text', models.CharField(max_length=1047)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RichTextSpanPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fractional_index', models.FloatField(blank=True, default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RichTextTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fractional_index', models.FloatField(blank=True, default=0.0)),
                ('text', models.CharField(max_length=255)),
                ('size', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RichTextTitlePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fractional_index', models.FloatField(blank=True, default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['created_at'], name='bookstore_t_created_dc6a5f_idx'),
        ),
        migrations.AddField(
            model_name='richtexttitleposition',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.article'),
        ),
        migrations.AddField(
            model_name='richtexttitleposition',
            name='rich_text_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.image'),
        ),
        migrations.AddIndex(
            model_name='richtexttitle',
            index=models.Index(fields=['created_at'], name='bookstore_r_created_eb3672_idx'),
        ),
        migrations.AddField(
            model_name='richtextspanposition',
            name='rich_text_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.richtextblock'),
        ),
        migrations.AddField(
            model_name='richtextspanposition',
            name='rich_text_span',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.richtextspan'),
        ),
        migrations.AddIndex(
            model_name='richtextspan',
            index=models.Index(fields=['created_at'], name='bookstore_r_created_413281_idx'),
        ),
        migrations.AddField(
            model_name='richtextblockposition',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.article'),
        ),
        migrations.AddField(
            model_name='richtextblockposition',
            name='rich_text_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.richtextblock'),
        ),
        migrations.AddIndex(
            model_name='richtextblock',
            index=models.Index(fields=['created_at'], name='bookstore_r_created_a453dc_idx'),
        ),
        migrations.AddField(
            model_name='imageposition',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.article'),
        ),
        migrations.AddField(
            model_name='imageposition',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.image'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['created_at'], name='bookstore_i_created_7eb023_idx'),
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['created_at'], name='bookstore_a_created_da62fc_idx'),
        ),
        migrations.AddField(
            model_name='articletopic',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.article'),
        ),
        migrations.AddField(
            model_name='articletopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.topic'),
        ),
        migrations.AddField(
            model_name='articleauthorship',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.article'),
        ),
        migrations.AddField(
            model_name='articleauthorship',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.author'),
        ),
        migrations.AddField(
            model_name='article',
            name='thumbnail_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.image'),
        ),
        migrations.AddIndex(
            model_name='richtexttitleposition',
            index=models.Index(fields=['created_at'], name='bookstore_r_created_27fcd1_idx'),
        ),
        migrations.AddIndex(
            model_name='richtextspanposition',
            index=models.Index(fields=['created_at'], name='bookstore_r_created_6068de_idx'),
        ),
        migrations.AddIndex(
            model_name='richtextblockposition',
            index=models.Index(fields=['created_at'], name='bookstore_r_created_612e16_idx'),
        ),
        migrations.AddIndex(
            model_name='imageposition',
            index=models.Index(fields=['created_at'], name='bookstore_i_created_3ab6e6_idx'),
        ),
        migrations.AddIndex(
            model_name='articletopic',
            index=models.Index(fields=['created_at'], name='bookstore_a_created_35e1d0_idx'),
        ),
        migrations.AddIndex(
            model_name='articleauthorship',
            index=models.Index(fields=['created_at'], name='bookstore_a_created_9ca949_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['created_at'], name='bookstore_a_created_d11fee_idx'),
        ),
    ]
