# Generated by Django 4.0.2 on 2022-02-14 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoreLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('street_address', models.CharField(max_length=255)),
                ('state_or_province', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['created_at'], name='bookstore_a_created_da62fc_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['created_at'], name='bookstore_b_created_9e43dd_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['created_at'], name='bookstore_c_created_71449b_idx'),
        ),
        migrations.AddIndex(
            model_name='storelocation',
            index=models.Index(fields=['created_at'], name='bookstore_s_created_668035_idx'),
        ),
        migrations.AddField(
            model_name='bookinventory',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.book'),
        ),
        migrations.AddField(
            model_name='bookinventory',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.storelocation'),
        ),
        migrations.AddIndex(
            model_name='bookinventory',
            index=models.Index(fields=['created_at'], name='bookstore_b_created_ce1a6c_idx'),
        ),
    ]
